trigger:
- main
pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'
steps:

- script: | 
      dir
      dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(System.DefaultWorkingDirectory)/DI-Framework


- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: './DI-Framework/DI-Framework/DI-Framework.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber
    arguments: '--configuration $(buildConfiguration)'
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: "Publishing new nuget package version"
  inputs:
    command: 'push'
    packagesToPush: '/home/vsts/work/1/a/DI-Framework.1.0.0-CI-20221104-125308.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(System.TeamProject)/DI-Framework/'
    allowPackageConflicts: false
    verbosityPush: "Normal"