trigger:
- develop

pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'
steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'
  workingDirectory: $(System.DefaultWorkingDirectory)/DI-Framework

- script: dotnet test
  displayName: 'Tests'
  workingDirectory: $(System.DefaultWorkingDirectory)/DI-Framework